version: '2'
services:
  web:
    build: crudcliente
    command: npm run start
    ports:
      - "3334:3334"
    networks:
          backend:
            ipv4_address: 172.35.0.6
    environment:
      - NODE_ENV=development
    depends_on:
      bd:
        condition: service_healthy
  api:
    build: api
    command: "npm run start"
    ports:
      - "3333:3333"
    networks:
          backend:
            ipv4_address: 172.35.0.2
    environment:
      NODE_ENV: "development"
    depends_on:
      bd:
        condition: service_healthy
  bd:
    build: bd
    ports:
      - "3306:3306"
    environment:
      NODE_ENV: "development"
      MYSQL_DATABASE: "cliente"
      MYSQL_USER: "teste"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PORT: "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
          backend:
            ipv4_address: 172.35.0.3
networks:
  backend:
    # Use a custom driver which takes special options
    driver: bridge
    ipam:
     config:
       - subnet: 172.35.0.0/16
         gateway: 172.35.0.1